# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-29 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homageapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='live_site',
            field=models.URLField(max_length=250),
        ),
    ]
